stages:
  - test
  - build
  - release

lint-golang:
  stage: test
  image: golangci/golangci-lint:v2.8-alpine
  
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: 
        - "**/*.go"
        - ".gitlab-ci.yml"

  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GOCACHE: $CI_PROJECT_DIR/.go-build
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.golangci-lint

  cache:
    key: 
      files:
        - go.sum
      prefix: lint-client
    paths:
      - .go/pkg/mod
      - .go-build
      - .golangci-lint

  script:
    - golangci-lint run
build-client:
  stage: build
  image: golang:1.25-alpine
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - go build -o gamesync ./cmd/gamesync
  artifacts:
    paths:
      - gamesync
    expire_in: 15 min
  
build-server-binary:
  stage: build
  image: golang:1.25:alpine
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - go build -o server/gamesync-state ./cmd/gamesync-state
  artifacts:
    paths:
      - server/gamesync-state
    expire_in: 15 min

build-server:
  stage: build
  image: quay.io/buildah/stable:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - job: build-server-binary
      artifacts: true
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot

  script:
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - buildah build -t "$CI_REGISTRY_IMAGE:latest" ./server
    - buildah push "$CI_REGISTRY_IMAGE:latest"


release-latest:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - job: build-client
      artifacts: true
  script:
    - echo "Preparing release..."
    - apk add --no-cache curl

    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file gamesync "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gamesync/latest/gamesync"
      curl --request DELETE --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/latest" || true
      curl --request DELETE --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags/latest" || true

  release:
    name: "Latest Release"
    description: "Latest build from main branch (Commit $CI_COMMIT_SHORT_SHA)"
    tag_name: "latest"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "Download gamesync (latest)"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gamesync/latest/gamesync"
