stages:
  - build util
  - check
  - lint

variables:
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/mod"
  GOLANGCI_LINT_CACHE: "$CI_PROJECT_DIR/.cache/golangci-lint"
  GIT_IMAGE: $CI_REGISTRY_IMAGE/git:latest


.docker:
  services:
    - name: moby/buildkit:latest
      alias: buildkit
      command: ["buildkitd", "--addr", "tcp://0.0.0.0.1234"]
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build git image:
  stage: build util
  image: moby/buildkit:latest
  extends: .docker
  script: buildctl --addr tcp://buildkit:1234 build -t $GIT_IMAGE --push -f ./docker/git.Dockerfile .
  rules:
    - changes: 
      - docker/git.Dockerfile
      - .gitlab-ci.yml


check gitignore:
  stage: check
  image: $GIT_IMAGE
  script:
    - apk add --no-cache git
    - ./scripts/git-verify-ignore.sh
  rules:
    - when: always

lint api:
  stage: lint
  image: dshanley/vacuum
  script: vacuum --ext-refs lint --min-score 100 --pipeline-output api/*
  rules:
    - changes: 
      - api/*
      - .gitlab-ci.yml

lint go:
  stage: lint
  image: golangci/golangci-lint
  script: 
    - mkdir -p .cache/{go-build,mod,golangci-lint}
    - golangci-lint run
    - golangci-lint cache status
  cache:
    key:
      files:
        - go.sum
    paths:
      - .cache/go-build
      - .cache/mod
      - .cache/golangci-lint
    when: always
  rules:
    - changes: 
      - "**/*.go"
      - .gitlab-ci.yml
