include:
  - ./docker-compose-swagger.yml
services:
  gamesync:
    build: .
    container_name: gamesync
    ports:
      - "8080:8080"
    volumes:
      - ./data/sqlite_db:/srv/gamesync/sqlite_db
    environment:
      GAMESYNC_DEFAULT_ROLE_ID: "50"
      GAMESYNC_DISABLED_ROLES: "maintainer"
      GAMESYNC_REQUEST_LOGS: true
      GAMESYNC_DB_LOG_LEVEL: error
    depends_on:
      migrate:
        condition: service_completed_successfully
  migrate:
    build:
      dockerfile: docker/goose_sqlite.Dockerfile
      context: .
    volumes:
      - ./data/sqlite_db/:/db
    command: ["goose", "up"]
