services:
  gamesync:
    build: .
    container_name: gamesync
    environment:
      - GAMESYNC_LOOP=20
    ports:
      - "2828:22"
    volumes:
      - ./config:/config
      - ./data:/data
      - gamesync_host_keys:/etc/ssh/keys
      - /etc/localtime:/etc/localtime:ro
volumes:
  gamesync_host_keys:
