// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBranch = "branches"

// Branch mapped from table <branches>
type Branch struct {
	BranchID       int64  `gorm:"column:branch_id;primaryKey;autoIncrement:true" json:"branch_id"`
	RepoID         int64  `gorm:"column:repo_id;not null" json:"repo_id"`
	BranchName     string `gorm:"column:branch_name;not null" json:"branch_name"`
	HeadSnapshotID *int64 `gorm:"column:head_snapshot_id" json:"head_snapshot_id"`
}

// TableName Branch's table name
func (*Branch) TableName() string {
	return TableNameBranch
}
