// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	FileHash []uint8 `gorm:"column:file_hash;primaryKey" json:"file_hash"`
	Bytes    int64   `gorm:"column:bytes;not null" json:"bytes"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
