// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFileChunk = "file_chunks"

// FileChunk mapped from table <file_chunks>
type FileChunk struct {
	FileHash   []uint8 `gorm:"column:file_hash;primaryKey" json:"file_hash"`
	ChunkHash  []uint8 `gorm:"column:chunk_hash;not null" json:"chunk_hash"`
	ChunkOrder int16   `gorm:"column:chunk_order;primaryKey" json:"chunk_order"`
}

// TableName FileChunk's table name
func (*FileChunk) TableName() string {
	return TableNameFileChunk
}
