// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	PermID   int32  `gorm:"column:perm_id;primaryKey;autoIncrement:true" json:"perm_id"`
	PermName string `gorm:"column:perm_name;not null" json:"perm_name"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
