// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRepo = "repos"

// Repo mapped from table <repos>
type Repo struct {
	RepoID   int64  `gorm:"column:repo_id;primaryKey;autoIncrement:true" json:"repo_id"`
	UserID   int64  `gorm:"column:user_id;not null" json:"user_id"`
	RepoName string `gorm:"column:repo_name;not null" json:"repo_name"`
}

// TableName Repo's table name
func (*Repo) TableName() string {
	return TableNameRepo
}
