// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameToken = "tokens"

// Token mapped from table <tokens>
type Token struct {
	TokenID   int64   `gorm:"column:token_id;primaryKey;autoIncrement:true" json:"token_id"`
	UserID    int64   `gorm:"column:user_id;not null" json:"user_id"`
	TokenHash []uint8 `gorm:"column:token_hash;not null" json:"token_hash"`
}

// TableName Token's table name
func (*Token) TableName() string {
	return TableNameToken
}
