// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID   int32  `gorm:"column:user_id;primaryKey" json:"user_id"`
	UserName string `gorm:"column:user_name;not null" json:"user_name"`
	RoleID   int32  `gorm:"column:role_id;not null" json:"role_id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
