#!/bin/bash

if [[ -f /etc/gamesync.env ]]; then
    source /etc/gamesync.env
fi

saves_dir="/data/saves/$USER"

export RESTIC_REPOSITORY="/data/repos/$USER"
export RESTIC_PASSWORD_FILE="/config/restic_passwords/$USER"

CMD=$SSH_ORIGINAL_COMMAND

if [[ "$GAMESYNC_UNRESTRICTED" == "true" ]]; then
    >&2 echo "Running command unrestricted, only use this for testing!"
    bash -c "$CMD"
    exit $?
fi

if [[ -z "$CMD" ]]; then
    exit 0
fi

if echo "$CMD" | grep -q '[;&|]'; then
    echo "Access Denied: Complex commands are not allowed."
    exit 1
fi

case "$CMD" in
    rsync\ *)
        bash -c "$CMD"
        ;;
    restic\ *)
        bash -c "$CMD"
        ;;
    mkdir\ *)
        bash -c "$CMD"
        ;;
    rm\ *)
        bash -c "$CMD"
        ;;
    gamesync-state\ *)
        bash -c "$CMD"
        ;;
    ls)
        ls -1 "$saves_dir"
        ;;
    *)
        echo "Access Denied: Invalid command."
        exit 1
        ;;
esac

exit $?
