#!/bin/bash

if [[ -f /etc/gamesync.env ]]; then
    source /etc/gamesync.env
fi

saves_dir="/data/saves/$USER"

export RESTIC_REPOSITORY="/data/repos/$USER"
export RESTIC_PASSWORD_FILE="/config/restic_passwords/$USER/current"

CMD=$SSH_ORIGINAL_COMMAND

if [[ -z "$CMD" ]]; then
    exit 0
fi

forbidden_chars=$'[&;|`$()<>\n\\]'
if [[ "$CMD" =~ $forbidden_chars ]] && [[ "$GAMESYNC_UNRESTRICTED" != "true" ]]; then
    echo "Access Denied: Complex commands are not allowed."
    exit 1
fi

case "$CMD" in
    rsync\ *)
        bash -c "$CMD"
        ;;
    restic\ *)
        bash -c "$CMD"
        ;;
    mkdir\ *)
        bash -c "$CMD"
        ;;
    rm\ *)
        bash -c "$CMD"
        ;;
    gamesync-state\ *)
        bash -c "$CMD"
        ;;
    list-saves)
        ls -1 "$saves_dir"
        ;;
    get-restic-password)
        cat "$RESTIC_PASSWORD_FILE"
        ;;
    *)
        if [[ "$GAMESYNC_UNRESTRICTED" == "true" ]]; then
            bash -c "$CMD"
            exit $?
        else
            echo "Access Denied: Invalid command."
            exit 1
        fi
        ;;
esac

exit $?
