#!/bin/sh

CMD=$SSH_ORIGINAL_COMMAND

if echo "$CMD" | grep -q '[;&|]'; then
    echo "Access Denied: Complex commands are not allowed."
    exit 1
fi

case "$CMD" in
    rsync*)
        exec /usr/bin/rsync $CMD
        ;;
    restic*)
        exec /usr/bin/restic $CMD
        ;;
    *)
        echo "Access Denied: Invalid command."
        exit 1
        ;;
esac
