PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
AuthenticationMethods publickey

HostKey /etc/ssh/keys/ssh_host_rsa_key
HostKey /etc/ssh/keys/ssh_host_ecdsa_key
HostKey /etc/ssh/keys/ssh_host_ed25519_key

AuthorizedKeysCommand /usr/local/bin/gamesync-auth %f
AuthorizedKeysCommandUser gamesync

AllowTcpForwarding no
X11Forwarding no
AllowAgentForwarding no
