// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gamesync/internal/model"
)

func newFileChunk(db *gorm.DB, opts ...gen.DOOption) fileChunk {
	_fileChunk := fileChunk{}

	_fileChunk.fileChunkDo.UseDB(db, opts...)
	_fileChunk.fileChunkDo.UseModel(&model.FileChunk{})

	tableName := _fileChunk.fileChunkDo.TableName()
	_fileChunk.ALL = field.NewAsterisk(tableName)
	_fileChunk.FileHash = field.NewField(tableName, "file_hash")
	_fileChunk.ChunkHash = field.NewField(tableName, "chunk_hash")
	_fileChunk.ChunkOrder = field.NewInt16(tableName, "chunk_order")

	_fileChunk.fillFieldMap()

	return _fileChunk
}

type fileChunk struct {
	fileChunkDo fileChunkDo

	ALL        field.Asterisk
	FileHash   field.Field
	ChunkHash  field.Field
	ChunkOrder field.Int16

	fieldMap map[string]field.Expr
}

func (f fileChunk) Table(newTableName string) *fileChunk {
	f.fileChunkDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileChunk) As(alias string) *fileChunk {
	f.fileChunkDo.DO = *(f.fileChunkDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileChunk) updateTableName(table string) *fileChunk {
	f.ALL = field.NewAsterisk(table)
	f.FileHash = field.NewField(table, "file_hash")
	f.ChunkHash = field.NewField(table, "chunk_hash")
	f.ChunkOrder = field.NewInt16(table, "chunk_order")

	f.fillFieldMap()

	return f
}

func (f *fileChunk) WithContext(ctx context.Context) IFileChunkDo {
	return f.fileChunkDo.WithContext(ctx)
}

func (f fileChunk) TableName() string { return f.fileChunkDo.TableName() }

func (f fileChunk) Alias() string { return f.fileChunkDo.Alias() }

func (f fileChunk) Columns(cols ...field.Expr) gen.Columns { return f.fileChunkDo.Columns(cols...) }

func (f *fileChunk) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileChunk) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 3)
	f.fieldMap["file_hash"] = f.FileHash
	f.fieldMap["chunk_hash"] = f.ChunkHash
	f.fieldMap["chunk_order"] = f.ChunkOrder
}

func (f fileChunk) clone(db *gorm.DB) fileChunk {
	f.fileChunkDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileChunk) replaceDB(db *gorm.DB) fileChunk {
	f.fileChunkDo.ReplaceDB(db)
	return f
}

type fileChunkDo struct{ gen.DO }

type IFileChunkDo interface {
	gen.SubQuery
	Debug() IFileChunkDo
	WithContext(ctx context.Context) IFileChunkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileChunkDo
	WriteDB() IFileChunkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileChunkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileChunkDo
	Not(conds ...gen.Condition) IFileChunkDo
	Or(conds ...gen.Condition) IFileChunkDo
	Select(conds ...field.Expr) IFileChunkDo
	Where(conds ...gen.Condition) IFileChunkDo
	Order(conds ...field.Expr) IFileChunkDo
	Distinct(cols ...field.Expr) IFileChunkDo
	Omit(cols ...field.Expr) IFileChunkDo
	Join(table schema.Tabler, on ...field.Expr) IFileChunkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileChunkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileChunkDo
	Group(cols ...field.Expr) IFileChunkDo
	Having(conds ...gen.Condition) IFileChunkDo
	Limit(limit int) IFileChunkDo
	Offset(offset int) IFileChunkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileChunkDo
	Unscoped() IFileChunkDo
	Create(values ...*model.FileChunk) error
	CreateInBatches(values []*model.FileChunk, batchSize int) error
	Save(values ...*model.FileChunk) error
	First() (*model.FileChunk, error)
	Take() (*model.FileChunk, error)
	Last() (*model.FileChunk, error)
	Find() ([]*model.FileChunk, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FileChunk, err error)
	FindInBatches(result *[]*model.FileChunk, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FileChunk) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileChunkDo
	Assign(attrs ...field.AssignExpr) IFileChunkDo
	Joins(fields ...field.RelationField) IFileChunkDo
	Preload(fields ...field.RelationField) IFileChunkDo
	FirstOrInit() (*model.FileChunk, error)
	FirstOrCreate() (*model.FileChunk, error)
	FindByPage(offset int, limit int) (result []*model.FileChunk, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileChunkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileChunkDo) Debug() IFileChunkDo {
	return f.withDO(f.DO.Debug())
}

func (f fileChunkDo) WithContext(ctx context.Context) IFileChunkDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileChunkDo) ReadDB() IFileChunkDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileChunkDo) WriteDB() IFileChunkDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileChunkDo) Session(config *gorm.Session) IFileChunkDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileChunkDo) Clauses(conds ...clause.Expression) IFileChunkDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileChunkDo) Returning(value interface{}, columns ...string) IFileChunkDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileChunkDo) Not(conds ...gen.Condition) IFileChunkDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileChunkDo) Or(conds ...gen.Condition) IFileChunkDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileChunkDo) Select(conds ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileChunkDo) Where(conds ...gen.Condition) IFileChunkDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileChunkDo) Order(conds ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileChunkDo) Distinct(cols ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileChunkDo) Omit(cols ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileChunkDo) Join(table schema.Tabler, on ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileChunkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileChunkDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileChunkDo) Group(cols ...field.Expr) IFileChunkDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileChunkDo) Having(conds ...gen.Condition) IFileChunkDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileChunkDo) Limit(limit int) IFileChunkDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileChunkDo) Offset(offset int) IFileChunkDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileChunkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileChunkDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileChunkDo) Unscoped() IFileChunkDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileChunkDo) Create(values ...*model.FileChunk) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileChunkDo) CreateInBatches(values []*model.FileChunk, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileChunkDo) Save(values ...*model.FileChunk) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileChunkDo) First() (*model.FileChunk, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileChunk), nil
	}
}

func (f fileChunkDo) Take() (*model.FileChunk, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileChunk), nil
	}
}

func (f fileChunkDo) Last() (*model.FileChunk, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileChunk), nil
	}
}

func (f fileChunkDo) Find() ([]*model.FileChunk, error) {
	result, err := f.DO.Find()
	return result.([]*model.FileChunk), err
}

func (f fileChunkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FileChunk, err error) {
	buf := make([]*model.FileChunk, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileChunkDo) FindInBatches(result *[]*model.FileChunk, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileChunkDo) Attrs(attrs ...field.AssignExpr) IFileChunkDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileChunkDo) Assign(attrs ...field.AssignExpr) IFileChunkDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileChunkDo) Joins(fields ...field.RelationField) IFileChunkDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileChunkDo) Preload(fields ...field.RelationField) IFileChunkDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileChunkDo) FirstOrInit() (*model.FileChunk, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileChunk), nil
	}
}

func (f fileChunkDo) FirstOrCreate() (*model.FileChunk, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileChunk), nil
	}
}

func (f fileChunkDo) FindByPage(offset int, limit int) (result []*model.FileChunk, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileChunkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileChunkDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileChunkDo) Delete(models ...*model.FileChunk) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileChunkDo) withDO(do gen.Dao) *fileChunkDo {
	f.DO = *do.(*gen.DO)
	return f
}
