// Code generated by "stringer -type=Perm -trimprefix=Perm"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermUsersDelete-0]
	_ = x[PermUsersUpdateName-1]
	_ = x[PermUsersUpdateNameOwn-2]
	_ = x[PermUsersUpdateRole-3]
	_ = x[PermRolesCreate-4]
	_ = x[PermRolesDelete-5]
	_ = x[PermRolesUpdateName-6]
	_ = x[PermRolesUpdatePerms-7]
}

const _Perm_name = "UsersDeleteUsersUpdateNameUsersUpdateNameOwnUsersUpdateRoleRolesCreateRolesDeleteRolesUpdateNameRolesUpdatePerms"

var _Perm_index = [...]uint8{0, 11, 26, 44, 59, 70, 81, 96, 112}

func (i Perm) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Perm_index)-1 {
		return "Perm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Perm_name[_Perm_index[idx]:_Perm_index[idx+1]]
}
