// Code generated by ogen, DO NOT EDIT.

package api

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// GetHealthOK is response for GetHealth operation.
type GetHealthOK struct{}

// GetPermsInternalServerError is response for GetPerms operation.
type GetPermsInternalServerError struct{}

func (*GetPermsInternalServerError) getPermsRes() {}

type GetPermsOKApplicationJSON []PermWithName

func (*GetPermsOKApplicationJSON) getPermsRes() {}

// GetPermsUnauthorized is response for GetPerms operation.
type GetPermsUnauthorized struct{}

func (*GetPermsUnauthorized) getPermsRes() {}

// GetRolePermsInternalServerError is response for GetRolePerms operation.
type GetRolePermsInternalServerError struct{}

func (*GetRolePermsInternalServerError) getRolePermsRes() {}

// GetRolePermsNotFound is response for GetRolePerms operation.
type GetRolePermsNotFound struct{}

func (*GetRolePermsNotFound) getRolePermsRes() {}

// GetRolePermsUnauthorized is response for GetRolePerms operation.
type GetRolePermsUnauthorized struct{}

func (*GetRolePermsUnauthorized) getRolePermsRes() {}

// GetRolesInternalServerError is response for GetRoles operation.
type GetRolesInternalServerError struct{}

func (*GetRolesInternalServerError) getRolesRes() {}

type GetRolesOKApplicationJSON []Role

func (*GetRolesOKApplicationJSON) getRolesRes() {}

// GetRolesUnauthorized is response for GetRoles operation.
type GetRolesUnauthorized struct{}

func (*GetRolesUnauthorized) getRolesRes() {}

// GetUserInternalServerError is response for GetUser operation.
type GetUserInternalServerError struct{}

func (*GetUserInternalServerError) getUserRes() {}

// GetUserNotFound is response for GetUser operation.
type GetUserNotFound struct{}

func (*GetUserNotFound) getUserRes() {}

// GetUserUnauthorized is response for GetUser operation.
type GetUserUnauthorized struct{}

func (*GetUserUnauthorized) getUserRes() {}

// GetUsersInternalServerError is response for GetUsers operation.
type GetUsersInternalServerError struct{}

func (*GetUsersInternalServerError) getUsersRes() {}

type GetUsersOKApplicationJSON []User

func (*GetUsersOKApplicationJSON) getUsersRes() {}

// GetUsersUnauthorized is response for GetUsers operation.
type GetUsersUnauthorized struct{}

func (*GetUsersUnauthorized) getUsersRes() {}

// NewOptPermDiff returns new OptPermDiff with value set to v.
func NewOptPermDiff(v PermDiff) OptPermDiff {
	return OptPermDiff{
		Value: v,
		Set:   true,
	}
}

// OptPermDiff is optional PermDiff.
type OptPermDiff struct {
	Value PermDiff
	Set   bool
}

// IsSet returns true if OptPermDiff was set.
func (o OptPermDiff) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPermDiff) Reset() {
	var v PermDiff
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPermDiff) SetTo(v PermDiff) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPermDiff) Get() (v PermDiff, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPermDiff) Or(d PermDiff) PermDiff {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRoleName returns new OptRoleName with value set to v.
func NewOptRoleName(v RoleName) OptRoleName {
	return OptRoleName{
		Value: v,
		Set:   true,
	}
}

// OptRoleName is optional RoleName.
type OptRoleName struct {
	Value RoleName
	Set   bool
}

// IsSet returns true if OptRoleName was set.
func (o OptRoleName) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRoleName) Reset() {
	var v RoleName
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRoleName) SetTo(v RoleName) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRoleName) Get() (v RoleName, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRoleName) Or(d RoleName) RoleName {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserName returns new OptUserName with value set to v.
func NewOptUserName(v UserName) OptUserName {
	return OptUserName{
		Value: v,
		Set:   true,
	}
}

// OptUserName is optional UserName.
type OptUserName struct {
	Value UserName
	Set   bool
}

// IsSet returns true if OptUserName was set.
func (o OptUserName) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserName) Reset() {
	var v UserName
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserName) SetTo(v UserName) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserName) Get() (v UserName, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserName) Or(d UserName) UserName {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PatchRolePermsCreated is response for PatchRolePerms operation.
type PatchRolePermsCreated struct{}

func (*PatchRolePermsCreated) patchRolePermsRes() {}

// PatchRolePermsInternalServerError is response for PatchRolePerms operation.
type PatchRolePermsInternalServerError struct{}

func (*PatchRolePermsInternalServerError) patchRolePermsRes() {}

// PatchRolePermsNotAcceptable is response for PatchRolePerms operation.
type PatchRolePermsNotAcceptable struct{}

func (*PatchRolePermsNotAcceptable) patchRolePermsRes() {}

// PatchRolePermsUnauthorized is response for PatchRolePerms operation.
type PatchRolePermsUnauthorized struct{}

func (*PatchRolePermsUnauthorized) patchRolePermsRes() {}

// PatchRolePermsUnprocessableEntity is response for PatchRolePerms operation.
type PatchRolePermsUnprocessableEntity struct{}

func (*PatchRolePermsUnprocessableEntity) patchRolePermsRes() {}

type Perm int32

// Ref: #/components/schemas/PermDiff
type PermDiff struct {
	Add    PermNameArray `json:"add"`
	Remove PermNameArray `json:"remove"`
}

// GetAdd returns the value of Add.
func (s *PermDiff) GetAdd() PermNameArray {
	return s.Add
}

// GetRemove returns the value of Remove.
func (s *PermDiff) GetRemove() PermNameArray {
	return s.Remove
}

// SetAdd sets the value of Add.
func (s *PermDiff) SetAdd(val PermNameArray) {
	s.Add = val
}

// SetRemove sets the value of Remove.
func (s *PermDiff) SetRemove(val PermNameArray) {
	s.Remove = val
}

type PermNameArray []string

func (*PermNameArray) getRolePermsRes() {}
func (*PermNameArray) putRolePermsRes() {}

// Merged schema.
// Ref: #/components/schemas/PermWithName
type PermWithName struct {
	PermID   Perm   `json:"permID"`
	PermName string `json:"permName"`
}

// GetPermID returns the value of PermID.
func (s *PermWithName) GetPermID() Perm {
	return s.PermID
}

// GetPermName returns the value of PermName.
func (s *PermWithName) GetPermName() string {
	return s.PermName
}

// SetPermID sets the value of PermID.
func (s *PermWithName) SetPermID(val Perm) {
	s.PermID = val
}

// SetPermName sets the value of PermName.
func (s *PermWithName) SetPermName(val string) {
	s.PermName = val
}

// PostRolesConflict is response for PostRoles operation.
type PostRolesConflict struct{}

func (*PostRolesConflict) postRolesRes() {}

// PostRolesInternalServerError is response for PostRoles operation.
type PostRolesInternalServerError struct{}

func (*PostRolesInternalServerError) postRolesRes() {}

// PostRolesNotAcceptable is response for PostRoles operation.
type PostRolesNotAcceptable struct{}

func (*PostRolesNotAcceptable) postRolesRes() {}

// PostRolesUnauthorized is response for PostRoles operation.
type PostRolesUnauthorized struct{}

func (*PostRolesUnauthorized) postRolesRes() {}

// PostUsersConflict is response for PostUsers operation.
type PostUsersConflict struct{}

func (*PostUsersConflict) postUsersRes() {}

// PostUsersInternalServerError is response for PostUsers operation.
type PostUsersInternalServerError struct{}

func (*PostUsersInternalServerError) postUsersRes() {}

// PostUsersNotAcceptable is response for PostUsers operation.
type PostUsersNotAcceptable struct{}

func (*PostUsersNotAcceptable) postUsersRes() {}

// PutRolePermsInternalServerError is response for PutRolePerms operation.
type PutRolePermsInternalServerError struct{}

func (*PutRolePermsInternalServerError) putRolePermsRes() {}

// PutRolePermsNotAcceptable is response for PutRolePerms operation.
type PutRolePermsNotAcceptable struct{}

func (*PutRolePermsNotAcceptable) putRolePermsRes() {}

// PutRolePermsUnauthorized is response for PutRolePerms operation.
type PutRolePermsUnauthorized struct{}

func (*PutRolePermsUnauthorized) putRolePermsRes() {}

// PutRolePermsUnprocessableEntity is response for PutRolePerms operation.
type PutRolePermsUnprocessableEntity struct{}

func (*PutRolePermsUnprocessableEntity) putRolePermsRes() {}

// PutUserNameInternalServerError is response for PutUserName operation.
type PutUserNameInternalServerError struct{}

func (*PutUserNameInternalServerError) putUserNameRes() {}

// PutUserNameNotAcceptable is response for PutUserName operation.
type PutUserNameNotAcceptable struct{}

func (*PutUserNameNotAcceptable) putUserNameRes() {}

// PutUserNameNotFound is response for PutUserName operation.
type PutUserNameNotFound struct{}

func (*PutUserNameNotFound) putUserNameRes() {}

// PutUserNameOK is response for PutUserName operation.
type PutUserNameOK struct{}

func (*PutUserNameOK) putUserNameRes() {}

// PutUserNameUnauthorized is response for PutUserName operation.
type PutUserNameUnauthorized struct{}

func (*PutUserNameUnauthorized) putUserNameRes() {}

// Merged schema.
// Ref: #/components/schemas/Role
type Role struct {
	RoleID   int32  `json:"roleID"`
	RoleName string `json:"roleName"`
}

// GetRoleID returns the value of RoleID.
func (s *Role) GetRoleID() int32 {
	return s.RoleID
}

// GetRoleName returns the value of RoleName.
func (s *Role) GetRoleName() string {
	return s.RoleName
}

// SetRoleID sets the value of RoleID.
func (s *Role) SetRoleID(val int32) {
	s.RoleID = val
}

// SetRoleName sets the value of RoleName.
func (s *Role) SetRoleName(val string) {
	s.RoleName = val
}

func (*Role) postRolesRes() {}

// Ref: #/components/schemas/_RoleName
type RoleName struct {
	RoleName string `json:"roleName"`
}

// GetRoleName returns the value of RoleName.
func (s *RoleName) GetRoleName() string {
	return s.RoleName
}

// SetRoleName sets the value of RoleName.
func (s *RoleName) SetRoleName(val string) {
	s.RoleName = val
}

// Merged schema.
// Ref: #/components/schemas/User
type User struct {
	UserID   int64  `json:"userID"`
	UserName string `json:"userName"`
	RoleID   int32  `json:"roleID"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() int64 {
	return s.UserID
}

// GetUserName returns the value of UserName.
func (s *User) GetUserName() string {
	return s.UserName
}

// GetRoleID returns the value of RoleID.
func (s *User) GetRoleID() int32 {
	return s.RoleID
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val int64) {
	s.UserID = val
}

// SetUserName sets the value of UserName.
func (s *User) SetUserName(val string) {
	s.UserName = val
}

// SetRoleID sets the value of RoleID.
func (s *User) SetRoleID(val int32) {
	s.RoleID = val
}

func (*User) getUserRes() {}

// Ref: #/components/schemas/_UserName
type UserName struct {
	UserName string `json:"userName"`
}

// GetUserName returns the value of UserName.
func (s *UserName) GetUserName() string {
	return s.UserName
}

// SetUserName sets the value of UserName.
func (s *UserName) SetUserName(val string) {
	s.UserName = val
}

// Merged schema.
// Ref: #/components/schemas/UserNewReturn
type UserNewReturn struct {
	UserID   int64  `json:"userID"`
	UserName string `json:"userName"`
	RoleID   int32  `json:"roleID"`
	Token    string `json:"token"`
}

// GetUserID returns the value of UserID.
func (s *UserNewReturn) GetUserID() int64 {
	return s.UserID
}

// GetUserName returns the value of UserName.
func (s *UserNewReturn) GetUserName() string {
	return s.UserName
}

// GetRoleID returns the value of RoleID.
func (s *UserNewReturn) GetRoleID() int32 {
	return s.RoleID
}

// GetToken returns the value of Token.
func (s *UserNewReturn) GetToken() string {
	return s.Token
}

// SetUserID sets the value of UserID.
func (s *UserNewReturn) SetUserID(val int64) {
	s.UserID = val
}

// SetUserName sets the value of UserName.
func (s *UserNewReturn) SetUserName(val string) {
	s.UserName = val
}

// SetRoleID sets the value of RoleID.
func (s *UserNewReturn) SetRoleID(val int32) {
	s.RoleID = val
}

// SetToken sets the value of Token.
func (s *UserNewReturn) SetToken(val string) {
	s.Token = val
}

func (*UserNewReturn) postUsersRes() {}
