// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetHealth implements get-health operation.
	//
	// Get health of server.
	//
	// GET /health
	GetHealth(ctx context.Context) error
	// GetPerms implements get-perms operation.
	//
	// Get all available permissions.
	//
	// GET /perms
	GetPerms(ctx context.Context) (GetPermsRes, error)
	// GetRolePerms implements get-role-perms operation.
	//
	// Get all permissions the role has.
	//
	// GET /roles/{roleID}/perms
	GetRolePerms(ctx context.Context, params GetRolePermsParams) (GetRolePermsRes, error)
	// GetRoles implements get-roles operation.
	//
	// Get all roles.
	//
	// GET /roles
	GetRoles(ctx context.Context) (GetRolesRes, error)
	// GetUser implements get-user operation.
	//
	// Get info about user.
	//
	// GET /users/{userID}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// GetUsers implements get-users operation.
	//
	// Get all users.
	//
	// GET /users
	GetUsers(ctx context.Context) (GetUsersRes, error)
	// PatchRolePerms implements patch-role-perms operation.
	//
	// Patch perms for role.
	//
	// PATCH /roles/{roleID}/perms
	PatchRolePerms(ctx context.Context, req OptPermDiff, params PatchRolePermsParams) (PatchRolePermsRes, error)
	// PostRoles implements post-roles operation.
	//
	// Create new role.
	//
	// POST /roles
	PostRoles(ctx context.Context, req OptRoleName) (PostRolesRes, error)
	// PostUsers implements post-users operation.
	//
	// Create new user.
	//
	// POST /users
	PostUsers(ctx context.Context, req OptUserNew) (PostUsersRes, error)
	// PutRolePerms implements put-role-perms operation.
	//
	// Set perms for role.
	//
	// PUT /roles/{roleID}/perms
	PutRolePerms(ctx context.Context, req PermArray, params PutRolePermsParams) (PutRolePermsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
