// Code generated by ogen, DO NOT EDIT.
package api

type PatchRolePermsRes interface {
	patchRolePermsRes()
}

type PostUserRepoBranchSnapshotRes interface {
	postUserRepoBranchSnapshotRes()
}

type PutChunkRes interface {
	putChunkRes()
}

type PutRolePermsRes interface {
	putRolePermsRes()
}
