// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetBranchHeadOperation  OperationName = "GetBranchHead"
	GetBranchesOperation    OperationName = "GetBranches"
	GetChunkOperation       OperationName = "GetChunk"
	GetHealthOperation      OperationName = "GetHealth"
	GetMeOperation          OperationName = "GetMe"
	GetPermsOperation       OperationName = "GetPerms"
	GetReposOperation       OperationName = "GetRepos"
	GetRolePermsOperation   OperationName = "GetRolePerms"
	GetRolesOperation       OperationName = "GetRoles"
	GetSnapshotOperation    OperationName = "GetSnapshot"
	GetUserOperation        OperationName = "GetUser"
	GetUsersOperation       OperationName = "GetUsers"
	PatchRolePermsOperation OperationName = "PatchRolePerms"
	PostRolesOperation      OperationName = "PostRoles"
	PostSnapshotOperation   OperationName = "PostSnapshot"
	PostUsersOperation      OperationName = "PostUsers"
	PutBranchOperation      OperationName = "PutBranch"
	PutChunkOperation       OperationName = "PutChunk"
	PutRepoOperation        OperationName = "PutRepo"
	PutRoleNameOperation    OperationName = "PutRoleName"
	PutRolePermsOperation   OperationName = "PutRolePerms"
	PutUserNameOperation    OperationName = "PutUserName"
)
