// Code generated by ogen, DO NOT EDIT.
package api

type GetPermsRes interface {
	getPermsRes()
}

type GetRolePermsRes interface {
	getRolePermsRes()
}

type GetRolesRes interface {
	getRolesRes()
}

type GetUserRepoBranchesRes interface {
	getUserRepoBranchesRes()
}

type GetUserReposRes interface {
	getUserReposRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type PatchRolePermsRes interface {
	patchRolePermsRes()
}

type PostChunkRes interface {
	postChunkRes()
}

type PostRolesRes interface {
	postRolesRes()
}

type PostUserRepoBranchSnapshotRes interface {
	postUserRepoBranchSnapshotRes()
}

type PostUsersRes interface {
	postUsersRes()
}

type PutRoleNameRes interface {
	putRoleNameRes()
}

type PutRolePermsRes interface {
	putRolePermsRes()
}

type PutUserNameRes interface {
	putUserNameRes()
}

type PutUserRepoBranchRes interface {
	putUserRepoBranchRes()
}

type PutUserRepoRes interface {
	putUserRepoRes()
}
