// Code generated by ogen, DO NOT EDIT.

package api

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// GetHealthOK is response for GetHealth operation.
type GetHealthOK struct{}

// GetPermsInternalServerError is response for GetPerms operation.
type GetPermsInternalServerError struct{}

func (*GetPermsInternalServerError) getPermsRes() {}

type GetPermsOKApplicationJSON []PermWithName

func (*GetPermsOKApplicationJSON) getPermsRes() {}

// GetRolePermsInternalServerError is response for GetRolePerms operation.
type GetRolePermsInternalServerError struct{}

func (*GetRolePermsInternalServerError) getRolePermsRes() {}

// GetRolesInternalServerError is response for GetRoles operation.
type GetRolesInternalServerError struct{}

func (*GetRolesInternalServerError) getRolesRes() {}

type GetRolesOKApplicationJSON []Role

func (*GetRolesOKApplicationJSON) getRolesRes() {}

// GetUserIDOK is response for GetUserID operation.
type GetUserIDOK struct{}

// GetUsersInternalServerError is response for GetUsers operation.
type GetUsersInternalServerError struct{}

func (*GetUsersInternalServerError) getUsersRes() {}

type GetUsersOKApplicationJSON []User

func (*GetUsersOKApplicationJSON) getUsersRes() {}

// NewOptPermDiff returns new OptPermDiff with value set to v.
func NewOptPermDiff(v PermDiff) OptPermDiff {
	return OptPermDiff{
		Value: v,
		Set:   true,
	}
}

// OptPermDiff is optional PermDiff.
type OptPermDiff struct {
	Value PermDiff
	Set   bool
}

// IsSet returns true if OptPermDiff was set.
func (o OptPermDiff) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPermDiff) Reset() {
	var v PermDiff
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPermDiff) SetTo(v PermDiff) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPermDiff) Get() (v PermDiff, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPermDiff) Or(d PermDiff) PermDiff {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRoleNew returns new OptRoleNew with value set to v.
func NewOptRoleNew(v RoleNew) OptRoleNew {
	return OptRoleNew{
		Value: v,
		Set:   true,
	}
}

// OptRoleNew is optional RoleNew.
type OptRoleNew struct {
	Value RoleNew
	Set   bool
}

// IsSet returns true if OptRoleNew was set.
func (o OptRoleNew) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRoleNew) Reset() {
	var v RoleNew
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRoleNew) SetTo(v RoleNew) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRoleNew) Get() (v RoleNew, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRoleNew) Or(d RoleNew) RoleNew {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserNew returns new OptUserNew with value set to v.
func NewOptUserNew(v UserNew) OptUserNew {
	return OptUserNew{
		Value: v,
		Set:   true,
	}
}

// OptUserNew is optional UserNew.
type OptUserNew struct {
	Value UserNew
	Set   bool
}

// IsSet returns true if OptUserNew was set.
func (o OptUserNew) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserNew) Reset() {
	var v UserNew
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserNew) SetTo(v UserNew) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserNew) Get() (v UserNew, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserNew) Or(d UserNew) UserNew {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PatchRolePermsInternalServerError is response for PatchRolePerms operation.
type PatchRolePermsInternalServerError struct{}

func (*PatchRolePermsInternalServerError) patchRolePermsRes() {}

// PatchRolePermsNotAcceptable is response for PatchRolePerms operation.
type PatchRolePermsNotAcceptable struct{}

func (*PatchRolePermsNotAcceptable) patchRolePermsRes() {}

type Perm int32

type PermArray []Perm

func (*PermArray) getRolePermsRes()   {}
func (*PermArray) patchRolePermsRes() {}
func (*PermArray) putRolePermsRes()   {}

// Ref: #/components/schemas/PermDiff
type PermDiff struct {
	Add    PermArray `json:"add"`
	Remove PermArray `json:"remove"`
}

// GetAdd returns the value of Add.
func (s *PermDiff) GetAdd() PermArray {
	return s.Add
}

// GetRemove returns the value of Remove.
func (s *PermDiff) GetRemove() PermArray {
	return s.Remove
}

// SetAdd sets the value of Add.
func (s *PermDiff) SetAdd(val PermArray) {
	s.Add = val
}

// SetRemove sets the value of Remove.
func (s *PermDiff) SetRemove(val PermArray) {
	s.Remove = val
}

// Ref: #/components/schemas/PermWithName
type PermWithName struct {
	PermID   Perm   `json:"permID"`
	PermName string `json:"permName"`
}

// GetPermID returns the value of PermID.
func (s *PermWithName) GetPermID() Perm {
	return s.PermID
}

// GetPermName returns the value of PermName.
func (s *PermWithName) GetPermName() string {
	return s.PermName
}

// SetPermID sets the value of PermID.
func (s *PermWithName) SetPermID(val Perm) {
	s.PermID = val
}

// SetPermName sets the value of PermName.
func (s *PermWithName) SetPermName(val string) {
	s.PermName = val
}

// PostRolesConflict is response for PostRoles operation.
type PostRolesConflict struct{}

func (*PostRolesConflict) postRolesRes() {}

// PostRolesInternalServerError is response for PostRoles operation.
type PostRolesInternalServerError struct{}

func (*PostRolesInternalServerError) postRolesRes() {}

// PostRolesNotAcceptable is response for PostRoles operation.
type PostRolesNotAcceptable struct{}

func (*PostRolesNotAcceptable) postRolesRes() {}

// PostUsersConflict is response for PostUsers operation.
type PostUsersConflict struct{}

func (*PostUsersConflict) postUsersRes() {}

// PostUsersInternalServerError is response for PostUsers operation.
type PostUsersInternalServerError struct{}

func (*PostUsersInternalServerError) postUsersRes() {}

// PostUsersNotAcceptable is response for PostUsers operation.
type PostUsersNotAcceptable struct{}

func (*PostUsersNotAcceptable) postUsersRes() {}

// PutRolePermsInternalServerError is response for PutRolePerms operation.
type PutRolePermsInternalServerError struct{}

func (*PutRolePermsInternalServerError) putRolePermsRes() {}

// PutRolePermsNotAcceptable is response for PutRolePerms operation.
type PutRolePermsNotAcceptable struct{}

func (*PutRolePermsNotAcceptable) putRolePermsRes() {}

// Ref: #/components/schemas/Role
type Role struct {
	RoleName string `json:"roleName"`
	RoleID   int32  `json:"roleID"`
}

// GetRoleName returns the value of RoleName.
func (s *Role) GetRoleName() string {
	return s.RoleName
}

// GetRoleID returns the value of RoleID.
func (s *Role) GetRoleID() int32 {
	return s.RoleID
}

// SetRoleName sets the value of RoleName.
func (s *Role) SetRoleName(val string) {
	s.RoleName = val
}

// SetRoleID sets the value of RoleID.
func (s *Role) SetRoleID(val int32) {
	s.RoleID = val
}

func (*Role) postRolesRes() {}

// Ref: #/components/schemas/RoleNew
type RoleNew struct {
	RoleName string `json:"roleName"`
}

// GetRoleName returns the value of RoleName.
func (s *RoleNew) GetRoleName() string {
	return s.RoleName
}

// SetRoleName sets the value of RoleName.
func (s *RoleNew) SetRoleName(val string) {
	s.RoleName = val
}

// Ref: #/components/schemas/User
type User struct {
	UserID   int64  `json:"userID"`
	UserName string `json:"userName"`
	RoleID   int32  `json:"roleID"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() int64 {
	return s.UserID
}

// GetUserName returns the value of UserName.
func (s *User) GetUserName() string {
	return s.UserName
}

// GetRoleID returns the value of RoleID.
func (s *User) GetRoleID() int32 {
	return s.RoleID
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val int64) {
	s.UserID = val
}

// SetUserName sets the value of UserName.
func (s *User) SetUserName(val string) {
	s.UserName = val
}

// SetRoleID sets the value of RoleID.
func (s *User) SetRoleID(val int32) {
	s.RoleID = val
}

// Ref: #/components/schemas/UserNew
type UserNew struct {
	UserName string `json:"userName"`
	RoleID   int32  `json:"roleID"`
}

// GetUserName returns the value of UserName.
func (s *UserNew) GetUserName() string {
	return s.UserName
}

// GetRoleID returns the value of RoleID.
func (s *UserNew) GetRoleID() int32 {
	return s.RoleID
}

// SetUserName sets the value of UserName.
func (s *UserNew) SetUserName(val string) {
	s.UserName = val
}

// SetRoleID sets the value of RoleID.
func (s *UserNew) SetRoleID(val int32) {
	s.RoleID = val
}

// Ref: #/components/schemas/UserNewReturn
type UserNewReturn struct {
	UserID   int64  `json:"userID"`
	UserName string `json:"userName"`
	RoleID   int32  `json:"roleID"`
	Token    string `json:"token"`
}

// GetUserID returns the value of UserID.
func (s *UserNewReturn) GetUserID() int64 {
	return s.UserID
}

// GetUserName returns the value of UserName.
func (s *UserNewReturn) GetUserName() string {
	return s.UserName
}

// GetRoleID returns the value of RoleID.
func (s *UserNewReturn) GetRoleID() int32 {
	return s.RoleID
}

// GetToken returns the value of Token.
func (s *UserNewReturn) GetToken() string {
	return s.Token
}

// SetUserID sets the value of UserID.
func (s *UserNewReturn) SetUserID(val int64) {
	s.UserID = val
}

// SetUserName sets the value of UserName.
func (s *UserNewReturn) SetUserName(val string) {
	s.UserName = val
}

// SetRoleID sets the value of RoleID.
func (s *UserNewReturn) SetRoleID(val int32) {
	s.RoleID = val
}

// SetToken sets the value of Token.
func (s *UserNewReturn) SetToken(val string) {
	s.Token = val
}

func (*UserNewReturn) postUsersRes() {}
