// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s GetUsersOKApplicationJSON) Validate() error {
	alias := ([]jx.Raw)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
