// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthOperation      OperationName = "GetHealth"
	GetPermsOperation       OperationName = "GetPerms"
	GetRolePermsOperation   OperationName = "GetRolePerms"
	GetRolesOperation       OperationName = "GetRoles"
	GetUserOperation        OperationName = "GetUser"
	GetUsersOperation       OperationName = "GetUsers"
	PatchRolePermsOperation OperationName = "PatchRolePerms"
	PostRolesOperation      OperationName = "PostRoles"
	PostUsersOperation      OperationName = "PostUsers"
	PutRolePermsOperation   OperationName = "PutRolePerms"
	PutUserNameOperation    OperationName = "PutUserName"
)
