// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements get-health operation.
//
// Get health of server.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetPerms implements get-perms operation.
//
// Get all available permissions.
//
// GET /perms
func (UnimplementedHandler) GetPerms(ctx context.Context) (r GetPermsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRolePerms implements get-role-perms operation.
//
// Get all permissions the role has.
//
// GET /roles/{roleID}/perms
func (UnimplementedHandler) GetRolePerms(ctx context.Context, params GetRolePermsParams) (r GetRolePermsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoles implements get-roles operation.
//
// Get all roles.
//
// GET /roles
func (UnimplementedHandler) GetRoles(ctx context.Context) (r GetRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements get-user operation.
//
// Get info about user.
//
// GET /users/{userID}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserRepoBranches implements get-user-repo-branches operation.
//
// Get all branches in repo.
//
// GET /users/{userID}/repos/{repoName}/branches
func (UnimplementedHandler) GetUserRepoBranches(ctx context.Context, params GetUserRepoBranchesParams) (r GetUserRepoBranchesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserRepos implements get-user-repos operation.
//
// Get all repos owned by userID.
//
// GET /users/{userID}/repos
func (UnimplementedHandler) GetUserRepos(ctx context.Context, params GetUserReposParams) (r GetUserReposRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements get-users operation.
//
// Get all users.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchRolePerms implements patch-role-perms operation.
//
// Patch perms for role.
//
// PATCH /roles/{roleID}/perms
func (UnimplementedHandler) PatchRolePerms(ctx context.Context, req OptPermDiff, params PatchRolePermsParams) (r PatchRolePermsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostRoles implements post-roles operation.
//
// Create new role.
//
// POST /roles
func (UnimplementedHandler) PostRoles(ctx context.Context, req OptRoleName) (r PostRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostUserRepoBranchSnapshot implements post-user-repo-branch-snapshot operation.
//
// Create new snapshot.
//
// POST /users/{userID}/repos/{repoName}/branches/{branchName}/snapshots
func (UnimplementedHandler) PostUserRepoBranchSnapshot(ctx context.Context, req OptSnapshotNew, params PostUserRepoBranchSnapshotParams) (r PostUserRepoBranchSnapshotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostUsers implements post-users operation.
//
// Create new user.
//
// POST /users
func (UnimplementedHandler) PostUsers(ctx context.Context, req OptUserName) (r PostUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutChunk implements put-chunk operation.
//
// Upload chunk.
//
// PUT /chunks/{chunkHash}
func (UnimplementedHandler) PutChunk(ctx context.Context, req PutChunkReq, params PutChunkParams) (r PutChunkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutRoleName implements put-role-name operation.
//
// Update role name.
//
// PUT /roles/{roleID}/name
func (UnimplementedHandler) PutRoleName(ctx context.Context, req OptRoleName, params PutRoleNameParams) (r PutRoleNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutRolePerms implements put-role-perms operation.
//
// Set perms for role.
//
// PUT /roles/{roleID}/perms
func (UnimplementedHandler) PutRolePerms(ctx context.Context, req PermNameArray, params PutRolePermsParams) (r PutRolePermsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutUserName implements put-user-name operation.
//
// Change username of user.
//
// PUT /users/{userID}/name
func (UnimplementedHandler) PutUserName(ctx context.Context, req OptUserName, params PutUserNameParams) (r PutUserNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutUserRepo implements put-user-repo operation.
//
// Create new repo and a default branch "main".
//
// PUT /users/{userID}/repos/{repoName}
func (UnimplementedHandler) PutUserRepo(ctx context.Context, params PutUserRepoParams) (r PutUserRepoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutUserRepoBranch implements put-user-repo-branch operation.
//
// Create new branch in repo.
//
// PUT /users/{userID}/repos/{repoName}/branches/{branchName}
func (UnimplementedHandler) PutUserRepoBranch(ctx context.Context, params PutUserRepoBranchParams) (r PutUserRepoBranchRes, _ error) {
	return r, ht.ErrNotImplemented
}
