// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements get-health operation.
//
// Get health of server.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetRoles implements get-roles operation.
//
// Get all roles.
//
// GET /roles
func (UnimplementedHandler) GetRoles(ctx context.Context) (r GetRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserID implements get-user-id operation.
//
// Get info about user.
//
// GET /users/{user_id}
func (UnimplementedHandler) GetUserID(ctx context.Context, params GetUserIDParams) error {
	return ht.ErrNotImplemented
}

// GetUsers implements get-users operation.
//
// Get all users.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostRoles implements post-roles operation.
//
// Create new role.
//
// POST /roles
func (UnimplementedHandler) PostRoles(ctx context.Context, req OptRole) (r PostRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostUsers implements post-users operation.
//
// Create new user.
//
// POST /users
func (UnimplementedHandler) PostUsers(ctx context.Context, req OptUserNew) (r PostUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}
