// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"
)

// GetHealthOK is response for GetHealth operation.
type GetHealthOK struct{}

// GetRolesInternalServerError is response for GetRoles operation.
type GetRolesInternalServerError struct{}

func (*GetRolesInternalServerError) getRolesRes() {}

// GetRolesNotAcceptable is response for GetRoles operation.
type GetRolesNotAcceptable struct{}

func (*GetRolesNotAcceptable) getRolesRes() {}

// GetRolesOK is response for GetRoles operation.
type GetRolesOK struct{}

func (*GetRolesOK) getRolesRes() {}

// GetUserIDOK is response for GetUserID operation.
type GetUserIDOK struct{}

// GetUsersInternalServerError is response for GetUsers operation.
type GetUsersInternalServerError struct{}

func (*GetUsersInternalServerError) getUsersRes() {}

type GetUsersOKApplicationJSON []jx.Raw

func (*GetUsersOKApplicationJSON) getUsersRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRole returns new OptRole with value set to v.
func NewOptRole(v Role) OptRole {
	return OptRole{
		Value: v,
		Set:   true,
	}
}

// OptRole is optional Role.
type OptRole struct {
	Value Role
	Set   bool
}

// IsSet returns true if OptRole was set.
func (o OptRole) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRole) Reset() {
	var v Role
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRole) SetTo(v Role) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRole) Get() (v Role, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRole) Or(d Role) Role {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserNew returns new OptUserNew with value set to v.
func NewOptUserNew(v UserNew) OptUserNew {
	return OptUserNew{
		Value: v,
		Set:   true,
	}
}

// OptUserNew is optional UserNew.
type OptUserNew struct {
	Value UserNew
	Set   bool
}

// IsSet returns true if OptUserNew was set.
func (o OptUserNew) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserNew) Reset() {
	var v UserNew
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserNew) SetTo(v UserNew) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserNew) Get() (v UserNew, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserNew) Or(d UserNew) UserNew {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PostRolesInternalServerError is response for PostRoles operation.
type PostRolesInternalServerError struct{}

func (*PostRolesInternalServerError) postRolesRes() {}

// PostRolesNotAcceptable is response for PostRoles operation.
type PostRolesNotAcceptable struct{}

func (*PostRolesNotAcceptable) postRolesRes() {}

// PostUsersInternalServerError is response for PostUsers operation.
type PostUsersInternalServerError struct{}

func (*PostUsersInternalServerError) postUsersRes() {}

// PostUsersNotAcceptable is response for PostUsers operation.
type PostUsersNotAcceptable struct{}

func (*PostUsersNotAcceptable) postUsersRes() {}

// Ref: #/components/schemas/Role
type Role struct {
	RoleName string `json:"roleName"`
}

// GetRoleName returns the value of RoleName.
func (s *Role) GetRoleName() string {
	return s.RoleName
}

// SetRoleName sets the value of RoleName.
func (s *Role) SetRoleName(val string) {
	s.RoleName = val
}

// Ref: #/components/schemas/RoleNew
type RoleNew struct {
	RoleName string `json:"roleName"`
}

// GetRoleName returns the value of RoleName.
func (s *RoleNew) GetRoleName() string {
	return s.RoleName
}

// SetRoleName sets the value of RoleName.
func (s *RoleNew) SetRoleName(val string) {
	s.RoleName = val
}

func (*RoleNew) postRolesRes() {}

// Ref: #/components/schemas/User
type User struct {
	UserId   OptInt    `json:"userId"`
	UserName OptString `json:"userName"`
	RoleId   OptInt    `json:"roleId"`
	Token    OptString `json:"token"`
}

// GetUserId returns the value of UserId.
func (s *User) GetUserId() OptInt {
	return s.UserId
}

// GetUserName returns the value of UserName.
func (s *User) GetUserName() OptString {
	return s.UserName
}

// GetRoleId returns the value of RoleId.
func (s *User) GetRoleId() OptInt {
	return s.RoleId
}

// GetToken returns the value of Token.
func (s *User) GetToken() OptString {
	return s.Token
}

// SetUserId sets the value of UserId.
func (s *User) SetUserId(val OptInt) {
	s.UserId = val
}

// SetUserName sets the value of UserName.
func (s *User) SetUserName(val OptString) {
	s.UserName = val
}

// SetRoleId sets the value of RoleId.
func (s *User) SetRoleId(val OptInt) {
	s.RoleId = val
}

// SetToken sets the value of Token.
func (s *User) SetToken(val OptString) {
	s.Token = val
}

func (*User) postUsersRes() {}

// Ref: #/components/schemas/UserNew
type UserNew struct {
	UserName string `json:"userName"`
	RoleId   int    `json:"roleId"`
}

// GetUserName returns the value of UserName.
func (s *UserNew) GetUserName() string {
	return s.UserName
}

// GetRoleId returns the value of RoleId.
func (s *UserNew) GetRoleId() int {
	return s.RoleId
}

// SetUserName sets the value of UserName.
func (s *UserNew) SetUserName(val string) {
	s.UserName = val
}

// SetRoleId sets the value of RoleId.
func (s *UserNew) SetRoleId(val int) {
	s.RoleId = val
}
