// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/validate"
)

func decodeGetHealthResponse(resp *http.Response) (res *GetHealthOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &GetHealthOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeGetPermsResponse(resp *http.Response) (res GetPermsRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response GetPermsOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &GetPermsUnauthorized{}, nil
	case 500:
		// Code 500.
		return &GetPermsInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeGetRolePermsResponse(resp *http.Response) (res GetRolePermsRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response PermNameArray
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &GetRolePermsUnauthorized{}, nil
	case 404:
		// Code 404.
		return &GetRolePermsNotFound{}, nil
	case 500:
		// Code 500.
		return &GetRolePermsInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeGetRolesResponse(resp *http.Response) (res GetRolesRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response GetRolesOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &GetRolesUnauthorized{}, nil
	case 500:
		// Code 500.
		return &GetRolesInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeGetUserResponse(resp *http.Response) (res GetUserRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response User
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &GetUserUnauthorized{}, nil
	case 404:
		// Code 404.
		return &GetUserNotFound{}, nil
	case 500:
		// Code 500.
		return &GetUserInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeGetUsersResponse(resp *http.Response) (res GetUsersRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response GetUsersOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &GetUsersUnauthorized{}, nil
	case 500:
		// Code 500.
		return &GetUsersInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePatchRolePermsResponse(resp *http.Response) (res PatchRolePermsRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		return &PatchRolePermsCreated{}, nil
	case 401:
		// Code 401.
		return &PatchRolePermsUnauthorized{}, nil
	case 406:
		// Code 406.
		return &PatchRolePermsNotAcceptable{}, nil
	case 422:
		// Code 422.
		return &PatchRolePermsUnprocessableEntity{}, nil
	case 500:
		// Code 500.
		return &PatchRolePermsInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePostRolesResponse(resp *http.Response) (res PostRolesRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response Role
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &PostRolesUnauthorized{}, nil
	case 406:
		// Code 406.
		return &PostRolesNotAcceptable{}, nil
	case 409:
		// Code 409.
		return &PostRolesConflict{}, nil
	case 500:
		// Code 500.
		return &PostRolesInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePostUsersResponse(resp *http.Response) (res PostUsersRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response UserNewReturn
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 406:
		// Code 406.
		return &PostUsersNotAcceptable{}, nil
	case 409:
		// Code 409.
		return &PostUsersConflict{}, nil
	case 500:
		// Code 500.
		return &PostUsersInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePutRolePermsResponse(resp *http.Response) (res PutRolePermsRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response PermNameArray
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &PutRolePermsUnauthorized{}, nil
	case 406:
		// Code 406.
		return &PutRolePermsNotAcceptable{}, nil
	case 422:
		// Code 422.
		return &PutRolePermsUnprocessableEntity{}, nil
	case 500:
		// Code 500.
		return &PutRolePermsInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePutUserNameResponse(resp *http.Response) (res PutUserNameRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &PutUserNameOK{}, nil
	case 401:
		// Code 401.
		return &PutUserNameUnauthorized{}, nil
	case 404:
		// Code 404.
		return &PutUserNameNotFound{}, nil
	case 406:
		// Code 406.
		return &PutUserNameNotAcceptable{}, nil
	case 409:
		// Code 409.
		return &PutUserNameConflict{}, nil
	case 500:
		// Code 500.
		return &PutUserNameInternalServerError{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
