// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetHealth implements get-health operation.
	//
	// Get health of server.
	//
	// GET /health
	GetHealth(ctx context.Context) error
	// GetPerms implements get-perms operation.
	//
	// Get all available permissions.
	//
	// GET /perms
	GetPerms(ctx context.Context) (GetPermsRes, error)
	// GetRolePerms implements get-role-perms operation.
	//
	// Get all permissions the role has.
	//
	// GET /roles/{roleID}/perms
	GetRolePerms(ctx context.Context, params GetRolePermsParams) (GetRolePermsRes, error)
	// GetRoles implements get-roles operation.
	//
	// Get all roles.
	//
	// GET /roles
	GetRoles(ctx context.Context) (GetRolesRes, error)
	// GetUser implements get-user operation.
	//
	// Get info about user.
	//
	// GET /users/{userID}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// GetUserRepoBranches implements get-user-repo-branches operation.
	//
	// Get all branches in repo.
	//
	// GET /users/{userID}/repos/{repoName}/branches
	GetUserRepoBranches(ctx context.Context, params GetUserRepoBranchesParams) (GetUserRepoBranchesRes, error)
	// GetUserRepos implements get-user-repos operation.
	//
	// Get all repos owned by userID.
	//
	// GET /users/{userID}/repos
	GetUserRepos(ctx context.Context, params GetUserReposParams) (GetUserReposRes, error)
	// GetUsers implements get-users operation.
	//
	// Get all users.
	//
	// GET /users
	GetUsers(ctx context.Context) (GetUsersRes, error)
	// PatchRolePerms implements patch-role-perms operation.
	//
	// Patch perms for role.
	//
	// PATCH /roles/{roleID}/perms
	PatchRolePerms(ctx context.Context, req OptPermDiff, params PatchRolePermsParams) (PatchRolePermsRes, error)
	// PostRoles implements post-roles operation.
	//
	// Create new role.
	//
	// POST /roles
	PostRoles(ctx context.Context, req OptRoleName) (PostRolesRes, error)
	// PostUserRepoBranchSnapshot implements post-user-repo-branch-snapshot operation.
	//
	// Create new snapshot.
	//
	// POST /users/{userID}/repos/{repoName}/branches/{branchName}/snapshots
	PostUserRepoBranchSnapshot(ctx context.Context, req OptSnapshotNew, params PostUserRepoBranchSnapshotParams) (PostUserRepoBranchSnapshotRes, error)
	// PostUsers implements post-users operation.
	//
	// Create new user.
	//
	// POST /users
	PostUsers(ctx context.Context, req OptUserName) (PostUsersRes, error)
	// PutChunk implements put-chunk operation.
	//
	// Upload chunk.
	//
	// PUT /chunks/{chunkHash}
	PutChunk(ctx context.Context, req PutChunkReq, params PutChunkParams) (PutChunkRes, error)
	// PutRoleName implements put-role-name operation.
	//
	// Update role name.
	//
	// PUT /roles/{roleID}/name
	PutRoleName(ctx context.Context, req OptRoleName, params PutRoleNameParams) (PutRoleNameRes, error)
	// PutRolePerms implements put-role-perms operation.
	//
	// Set perms for role.
	//
	// PUT /roles/{roleID}/perms
	PutRolePerms(ctx context.Context, req PermNameArray, params PutRolePermsParams) (PutRolePermsRes, error)
	// PutUserName implements put-user-name operation.
	//
	// Change username of user.
	//
	// PUT /users/{userID}/name
	PutUserName(ctx context.Context, req OptUserName, params PutUserNameParams) (PutUserNameRes, error)
	// PutUserRepo implements put-user-repo operation.
	//
	// Create new repo and a default branch "main".
	//
	// PUT /users/{userID}/repos/{repoName}
	PutUserRepo(ctx context.Context, params PutUserRepoParams) (PutUserRepoRes, error)
	// PutUserRepoBranch implements put-user-repo-branch operation.
	//
	// Create new branch in repo.
	//
	// PUT /users/{userID}/repos/{repoName}/branches/{branchName}
	PutUserRepoBranch(ctx context.Context, params PutUserRepoBranchParams) (PutUserRepoBranchRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
