// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package dbm

import (
	"context"
)

const createBranch = `-- name: CreateBranch :exec
INSERT INTO branches (repo_id, branch_name)
VALUES ($1, $2)
`

type CreateBranchParams struct {
	RepoID     int64
	BranchName string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) error {
	_, err := q.db.Exec(ctx, createBranch, arg.RepoID, arg.BranchName)
	return err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches
WHERE repo_id = $1 AND branch_id = $2
`

type DeleteBranchParams struct {
	RepoID   int64
	BranchID int64
}

func (q *Queries) DeleteBranch(ctx context.Context, arg DeleteBranchParams) error {
	_, err := q.db.Exec(ctx, deleteBranch, arg.RepoID, arg.BranchID)
	return err
}

const getBranchWithName = `-- name: GetBranchWithName :one
SELECT branch_id, repo_id, branch_name, head_snapshot_id FROM branches
WHERE repo_id = $1
AND branch_name = $2
LIMIT 1
`

type GetBranchWithNameParams struct {
	RepoID     int64
	BranchName string
}

func (q *Queries) GetBranchWithName(ctx context.Context, arg GetBranchWithNameParams) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchWithName, arg.RepoID, arg.BranchName)
	var i Branch
	err := row.Scan(
		&i.BranchID,
		&i.RepoID,
		&i.BranchName,
		&i.HeadSnapshotID,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT branch_id, repo_id, branch_name, head_snapshot_id FROM branches
WHERE repo_id = (
    SELECT repo_id FROM repos 
    WHERE repo_name = $1
)
`

func (q *Queries) ListBranches(ctx context.Context, repoName string) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches, repoName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.BranchID,
			&i.RepoID,
			&i.BranchName,
			&i.HeadSnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
