// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbm

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Branch struct {
	BranchID       int64
	RepoID         int64
	BranchName     string
	HeadSnapshotID pgtype.Int8
}

type Chunk struct {
	ChunkHash []byte
}

type File struct {
	FileHash []byte
	Bytes    int64
}

type FileChunk struct {
	FileHash   []byte
	ChunkHash  []byte
	ChunkOrder int16
}

type Permission struct {
	PermID   int32
	PermName string
}

type Repo struct {
	RepoID   int64
	UserID   int64
	RepoName string
}

type Role struct {
	RoleID   int32
	RoleName string
}

type RolePermission struct {
	RolePermID int32
	RoleID     int32
	PermID     int32
}

type Snapshot struct {
	SnapshotID       int64
	ParentSnapshotID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
}

type SnapshotFile struct {
	FileHash   []byte
	SnapshotID int64
	FilePath   string
}

type Token struct {
	TokenID   int64
	UserID    int64
	TokenHash []byte
}

type User struct {
	UserID   int64
	UserName string
	RoleID   int32
}
