// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package dbm

import (
	"context"
)

const deletePermission = `-- name: DeletePermission :execrows
DELETE FROM permissions
WHERE perm_id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, permID int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermission, permID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPermission = `-- name: InsertPermission :exec
INSERT INTO permissions (perm_id, perm_name)
VALUES ($1, $2)
`

type InsertPermissionParams struct {
	PermID   int32
	PermName string
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) error {
	_, err := q.db.Exec(ctx, insertPermission, arg.PermID, arg.PermName)
	return err
}

const listPermIDsWithNames = `-- name: ListPermIDsWithNames :many
SELECT perm_id FROM permissions
WHERE perm_name = ANY($1::VARCHAR[])
`

func (q *Queries) ListPermIDsWithNames(ctx context.Context, permNames []string) ([]int32, error) {
	rows, err := q.db.Query(ctx, listPermIDsWithNames, permNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var perm_id int32
		if err := rows.Scan(&perm_id); err != nil {
			return nil, err
		}
		items = append(items, perm_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT perm_id, perm_name FROM permissions
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.PermID, &i.PermName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermsWithNames = `-- name: ListPermsWithNames :many
SELECT perm_id, perm_name FROM permissions
WHERE perm_name = ANY($1::VARCHAR[])
`

func (q *Queries) ListPermsWithNames(ctx context.Context, permNames []string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermsWithNames, permNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.PermID, &i.PermName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermissionName = `-- name: UpdatePermissionName :exec
UPDATE permissions
SET perm_name = $2
WHERE perm_id = $1
`

type UpdatePermissionNameParams struct {
	PermID   int32
	PermName string
}

func (q *Queries) UpdatePermissionName(ctx context.Context, arg UpdatePermissionNameParams) error {
	_, err := q.db.Exec(ctx, updatePermissionName, arg.PermID, arg.PermName)
	return err
}
