// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbm

import (
	"context"
)

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID int32) error {
	_, err := q.db.Exec(ctx, deleteRole, roleID)
	return err
}

const getRoleWithId = `-- name: GetRoleWithId :one
SELECT role_id, role_name FROM roles
WHERE role_id = $1
`

func (q *Queries) GetRoleWithId(ctx context.Context, roleID int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleWithId, roleID)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName)
	return i, err
}

const getRoleWithIdCount = `-- name: GetRoleWithIdCount :one
SELECT COUNT(*) FROM roles
WHERE role_id = $1
`

func (q *Queries) GetRoleWithIdCount(ctx context.Context, roleID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getRoleWithIdCount, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (role_name)
VALUES ($1)
RETURNING role_id
`

func (q *Queries) InsertRole(ctx context.Context, roleName string) (int32, error) {
	row := q.db.QueryRow(ctx, insertRole, roleName)
	var role_id int32
	err := row.Scan(&role_id)
	return role_id, err
}

const insertRoleWithId = `-- name: InsertRoleWithId :exec
INSERT INTO roles (role_id, role_name)
VALUES ($1, $2)
`

type InsertRoleWithIdParams struct {
	RoleID   int32
	RoleName string
}

func (q *Queries) InsertRoleWithId(ctx context.Context, arg InsertRoleWithIdParams) error {
	_, err := q.db.Exec(ctx, insertRoleWithId, arg.RoleID, arg.RoleName)
	return err
}

const listRoles = `-- name: ListRoles :many
SELECT role_id, role_name FROM roles
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleName = `-- name: UpdateRoleName :exec
UPDATE roles
SET role_name = $2
WHERE role_id = $1
`

type UpdateRoleNameParams struct {
	RoleID   int32
	RoleName string
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) error {
	_, err := q.db.Exec(ctx, updateRoleName, arg.RoleID, arg.RoleName)
	return err
}
