// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_permissions.sql

package dbm

import (
	"context"
)

const deleteRolePermsLT = `-- name: DeleteRolePermsLT :execrows
DELETE FROM role_permissions
WHERE role_id < $1
`

func (q *Queries) DeleteRolePermsLT(ctx context.Context, roleID int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRolePermsLT, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermsWithId = `-- name: DeleteRolePermsWithId :exec
DELETE FROM role_permissions
WHERE role_id = $1
AND perm_id = ANY($2::INTEGER[])
`

type DeleteRolePermsWithIdParams struct {
	RoleID  int32
	PermIds []int32
}

func (q *Queries) DeleteRolePermsWithId(ctx context.Context, arg DeleteRolePermsWithIdParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermsWithId, arg.RoleID, arg.PermIds)
	return err
}

const deleteRolePermsWithRoleId = `-- name: DeleteRolePermsWithRoleId :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermsWithRoleId(ctx context.Context, roleID int32) error {
	_, err := q.db.Exec(ctx, deleteRolePermsWithRoleId, roleID)
	return err
}

type InsertRolePermsParams struct {
	RoleID int32
	PermID int32
}

const insertRolePermsNoConflict = `-- name: InsertRolePermsNoConflict :exec
INSERT INTO role_permissions (role_id, perm_id)
SELECT $1, unnest($2::INTEGER[])
ON CONFLICT DO NOTHING
`

type InsertRolePermsNoConflictParams struct {
	RoleID  int32
	PermIds []int32
}

func (q *Queries) InsertRolePermsNoConflict(ctx context.Context, arg InsertRolePermsNoConflictParams) error {
	_, err := q.db.Exec(ctx, insertRolePermsNoConflict, arg.RoleID, arg.PermIds)
	return err
}

const listRolePermNamesWithName = `-- name: ListRolePermNamesWithName :many
SELECT perm_name FROM permissions
JOIN role_permissions USING (perm_id) 
WHERE role_permissions.role_id = $1
`

// returns slice of all the permissions a role has
//
// the returned permissions are their names
func (q *Queries) ListRolePermNamesWithName(ctx context.Context, roleID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermNamesWithName, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var perm_name string
		if err := rows.Scan(&perm_name); err != nil {
			return nil, err
		}
		items = append(items, perm_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePerms = `-- name: ListRolePerms :many
SELECT role_perm_id, role_id, perm_id FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) ListRolePerms(ctx context.Context, roleID int32) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePerms, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RolePermID, &i.RoleID, &i.PermID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
