// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_permissions.sql

package dbm

import (
	"context"
)

const deleteRolePermsLT = `-- name: DeleteRolePermsLT :execrows
DELETE FROM role_permissions
WHERE role_id < $1
`

func (q *Queries) DeleteRolePermsLT(ctx context.Context, roleID int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRolePermsLT, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type InsertRolePermsParams struct {
	RoleID int32
	PermID int32
}

const listRolePermNamesWithName = `-- name: ListRolePermNamesWithName :many
SELECT perm_name FROM permissions
JOIN role_permissions USING (perm_id) 
WHERE role_permissions.perm_id = $1
`

// returns slice of all the permissions a role has
//
// the returned permissions are their names
func (q *Queries) ListRolePermNamesWithName(ctx context.Context, permID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermNamesWithName, permID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var perm_name string
		if err := rows.Scan(&perm_name); err != nil {
			return nil, err
		}
		items = append(items, perm_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePerms = `-- name: ListRolePerms :many
SELECT role_perm_id, role_id, perm_id FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) ListRolePerms(ctx context.Context, roleID int32) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePerms, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RolePermID, &i.RoleID, &i.PermID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
