// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package dbm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConnectFileWithChunksParams struct {
	FileHash   []byte
	ChunkHash  []byte
	ChunkOrder int32
}

type ConnectSnapshotWithFilesParams struct {
	FileHash   []byte
	SnapshotID int64
	FilePath   string
}

const createFile = `-- name: CreateFile :exec
INSERT INTO files (file_hash, bytes)
VALUES (
    $1,
    (
        SELECT COALESCE(SUM(bytes), 0) FROM chunks
        WHERE chunk_hash = ANY($2::BYTEA[])
    )
)
`

type CreateFileParams struct {
	FileHash  []byte
	ChunkHash [][]byte
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile, arg.FileHash, arg.ChunkHash)
	return err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (parent_snapshot_id, repo_id)
VALUES (
    (
        SELECT head_snapshot_id FROM branches 
        WHERE repo_id = $1
        AND branch_id = $2
        LIMIT 1
    ),
    $1
)
RETURNING snapshot_id, parent_snapshot_id, repo_id, created_at
`

type CreateSnapshotParams struct {
	RepoID   int64
	BranchID int64
}

// returns the new snapshot_id
//
// also accepts branch_id to find the parent snapshot
// using head snapshot id from branches
func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot, arg.RepoID, arg.BranchID)
	var i Snapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.ParentSnapshotID,
		&i.RepoID,
		&i.CreatedAt,
	)
	return i, err
}

const getFileChunkHashes = `-- name: GetFileChunkHashes :many
SELECT chunk_hash FROM file_chunks
WHERE file_hash = $1
ORDER BY chunk_order
`

func (q *Queries) GetFileChunkHashes(ctx context.Context, fileHash []byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getFileChunkHashes, fileHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var chunk_hash []byte
		if err := rows.Scan(&chunk_hash); err != nil {
			return nil, err
		}
		items = append(items, chunk_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT snapshot_id, parent_snapshot_id, repo_id, created_at FROM snapshots
WHERE snapshot_id = $1
`

func (q *Queries) GetSnapshot(ctx context.Context, snapshotID int64) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, snapshotID)
	var i Snapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.ParentSnapshotID,
		&i.RepoID,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotFiles = `-- name: GetSnapshotFiles :many
SELECT snapshot_id, file_hash, file_path FROM snapshot_files
WHERE snapshot_id = $1
`

func (q *Queries) GetSnapshotFiles(ctx context.Context, snapshotID int64) ([]SnapshotFile, error) {
	rows, err := q.db.Query(ctx, getSnapshotFiles, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotFile
	for rows.Next() {
		var i SnapshotFile
		if err := rows.Scan(&i.SnapshotID, &i.FileHash, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileHashes = `-- name: ListFileHashes :many
SELECT file_hash FROM files
WHERE file_hash = ANY($1::BYTEA[])
`

func (q *Queries) ListFileHashes(ctx context.Context, fileHash [][]byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listFileHashes, fileHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var file_hash []byte
		if err := rows.Scan(&file_hash); err != nil {
			return nil, err
		}
		items = append(items, file_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranchHead = `-- name: UpdateBranchHead :exec
UPDATE branches
SET head_snapshot_id = $2
WHERE branch_id = $1
`

type UpdateBranchHeadParams struct {
	BranchID       int64
	HeadSnapshotID pgtype.Int8
}

func (q *Queries) UpdateBranchHead(ctx context.Context, arg UpdateBranchHeadParams) error {
	_, err := q.db.Exec(ctx, updateBranchHead, arg.BranchID, arg.HeadSnapshotID)
	return err
}
