// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbm

import (
	"context"
)

const getUserIdFromToken = `-- name: GetUserIdFromToken :one
SELECT user_id FROM tokens
WHERE token_hash = $1
`

func (q *Queries) GetUserIdFromToken(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIdFromToken, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO tokens (user_id, token_hash)
VALUES ($1, $2)
RETURNING token_id
`

type InsertTokenParams struct {
	UserID    int64
	TokenHash []byte
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertToken, arg.UserID, arg.TokenHash)
	var token_id int64
	err := row.Scan(&token_id)
	return token_id, err
}
