// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbm

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, user_name, role_id FROM users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.RoleID)
	return i, err
}

const getUserWithName = `-- name: GetUserWithName :one
SELECT user_id, user_name, role_id FROM users
WHERE user_name = $1
`

func (q *Queries) GetUserWithName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithName, userName)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.RoleID)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (user_name, role_id)
VALUES ($1, $2)
RETURNING user_id
`

type InsertUserParams struct {
	UserName string
	RoleID   int32
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.UserName, arg.RoleID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const insertUserWithId = `-- name: InsertUserWithId :exec
INSERT INTO users (user_id, user_name, role_id)
VALUES ($1, $2, $3)
`

type InsertUserWithIdParams struct {
	UserID   int64
	UserName string
	RoleID   int32
}

func (q *Queries) InsertUserWithId(ctx context.Context, arg InsertUserWithIdParams) error {
	_, err := q.db.Exec(ctx, insertUserWithId, arg.UserID, arg.UserName, arg.RoleID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_name, role_id FROM users
ORDER BY user_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.UserID, &i.UserName, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users
SET user_name = $2
WHERE user_id = $1
`

type UpdateUserNameParams struct {
	UserID   int64
	UserName string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.UserID, arg.UserName)
	return err
}
