openapi: 3.2.0
info:
  title: gamesync
  version: v1
  description: |
    Api spec for interacting with the Gamesync server
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: System
    description: system level stuff like health checks
  - name: Users
    description: managing users
    kind: nav
  - name: Roles
    description: managing roles
    kind: nav
  - name: Permissions
    description: managing permissions for roles
    parent: Roles
    kind: nav
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: opaque
  parameters:
    userID:
      name: userID
      description: Used to identify a user
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 0

    roleID:
      name: roleID
      description: Identify role
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
  schemas:

    ### base models
    _UserID:
      type: object
      properties:
        userID:
          type: integer
          format: int64
      required: [userID]
    _UserName:
      type: object
      properties:
        userName:
          type: string
      required: [userName]

    _RoleID:
      type: object
      properties:
        roleID:
          type: integer
          format: int32
      required: [roleID]
    _RoleName:
      type: object
      properties:
        roleName:
          type: string
      required: [roleName]

    _Perm:
      type: integer
      format: int32
    _PermID:
      type: object
      properties:
        permID:
          $ref: "#/components/schemas/_Perm"
      required: [permID]
    _PermName:
      type: object
      properties:
        permName:
          type: string
      required: [permName]

    ### User schemas
    UserNew:
      $ref: "#/components/schemas/_UserName"
    User:
      allOf:
        - $ref: "#/components/schemas/_UserID"
        - $ref: "#/components/schemas/_UserName"
        - $ref: "#/components/schemas/_RoleID"
    UserNewReturn:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            token:
              type: string
          required: [token]

    ### Role schemas
    RoleNew:
      $ref: "#/components/schemas/_RoleName"
    Role:
      allOf:
        - $ref: "#/components/schemas/_RoleID"
        - $ref: "#/components/schemas/_RoleName"

    ### Permission schemas
    PermWithName:
      allOf:
        - $ref: "#/components/schemas/_PermID"
        - $ref: "#/components/schemas/_PermName"
    PermNameArray:
      type: array
      items: 
        type: string
    PermDiff:
      type: object
      properties:
        add:
          $ref: "#/components/schemas/PermNameArray" 
        remove:
          $ref: "#/components/schemas/PermNameArray" 
      required:
        - add
        - remove


security:
  - bearerAuth: []

paths:
  /health:
    get:
      summary: Get health of server
      operationId: get-health
      tags:
        - System
      security: []
      responses:
        "200": {}


  /users:
    get:
      summary: Get all users
      operationId: get-users
      tags:
        - Users
      responses:
        "401": {}
        "200":
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500": {}
    post:
      summary: Create new user
      operationId: post-users
      tags:
        - Users
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserNew"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNewReturn"
        "406": {}
        "409": {}
        "500": {}
  /users/{userID}:
    parameters:
      - $ref: "#/components/parameters/userID"
    get:
      summary: Get info about user
      operationId: get-user
      tags:
        - Users
      responses:
        "401": {}
        "404": {}
        "200":
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500": {}



  /roles:
    get:
      summary: Get all roles
      operationId: get-roles
      tags:
        - Roles
      responses:
        "401": {}
        "200": 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"
        "500": {}
    post:
      summary: Create new role
      operationId: post-roles
      tags:
        - Roles
      responses:
        "401": {}
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
        "406": {}
        "409": {}
        "500": {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleNew"



  /roles/{roleID}/perms:
    parameters:
      - $ref: "#/components/parameters/roleID"
    get:
      summary: Get all permissions the role has
      operationId: get-role-perms
      tags:
        - Permissions
      responses:
        "401": {}
        "404": {}
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermNameArray"
        "500": {}
    patch:
      summary: Patch perms for role
      operationId: patch-role-perms
      tags:
        - Permissions
      responses:
        "401": {}
        "201": {}
        "406": {}
        "422":
          description: Any of the provided perms do not exist
        "500": {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PermDiff"
    put:
      summary: Set perms for role
      operationId: put-role-perms
      tags:
        - Permissions
      responses:
        "401": {}
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermNameArray"
        "406": {}
        "422":
          description: Any of the provided perms do not exist
        "500": {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PermNameArray"
  /perms:
    get:
      summary: Get all available permissions
      operationId: get-perms
      tags:
        - Permissions
      responses:
        "401": {}
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PermWithName"
        "500": {}

