openapi: 3.2.0
info:
  title: gamesync
  version: v1
  description: |
    Api spec for interacting with the Gamesync server
servers:
  - url: /api/v1
tags:
  - name: Other
  - name: Users
  - name: Roles
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: opaque
  parameters:
    user_id:
      description: Used to identify a user
      name: user_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 0
  schemas:
    UserNew:
      type: object
      properties:
        userName:
          type: string
        roleId:
          type: integer
          format: int32
      required:
        - userName
        - roleId
    UserNewReturn:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        userName:
          type: string
        roleId:
          type: integer
          format: int32
        token:
          type: string
      required:
        - userId
        - userName
        - roleId
        - token
    RoleNew:
      type: object
      properties:
        roleName:
          type: string
      required:
        - roleName
    Role:
      type: object
      properties:
        roleName:
          type: string
        roleId:
          type: integer
          format: int32
      required:
        - roleName
        - roleId


security:
  - bearerAuth: []

paths:
  /health:
    get:
      summary: Get health of server
      operationId: get-health
      tags:
        - Other
      security: []
      responses:
        "200": {}
  /users:
    get:
      summary: Get all users
      operationId: get-users
      tags:
        - Users
      responses:
        "200":
          content: 
            application/json:
              schema:
                type: array
        "500": {}
    post:
      summary: Create new user
      operationId: post-users
      tags:
        - Users
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserNew"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNewReturn"
        "406": {}
        "409": {}
        "500": {}
  /users/{user_id}:
    parameters:
      - $ref: "#/components/parameters/user_id"
    get:
      summary: Get info about user
      operationId: get-user-id
      tags:
        - Users
      responses:
        "200": {}

  /roles:
    get:
      summary: Get all roles
      operationId: get-roles
      tags:
        - Roles
      responses:
        "200": 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"
        "406": {}
        "500": {}
    post:
      summary: Create new role
      operationId: post-roles
      tags:
        - Roles
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
        "406": {}
        "409": {}
        "500": {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleNew"
