openapi: 3.2.0
info:
  title: gamesync
  version: v1
  description: |
    Api spec for interacting with the Gamesync server
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: System
    description: system level stuff like health checks

  - name: Users
    description: managing users
    kind: nav

  - name: Roles
    description: managing roles
    kind: nav

  - name: Permissions
    description: managing permissions for roles
    parent: Roles
    kind: nav

  - name: Chunk
    description: Upload or download chunk
    kind: nav

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: opaque
  parameters:
    userID:
      name: userID
      description: Used to identify a user
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 0

    roleID:
      name: roleID
      description: Identify role
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0

    repoName:
      name: repoName
      description: Identify repository
      in: path
      required: true
      schema:
        type: string
    branchName:
      name: branchName
      description: Identify branch
      in: path
      required: true
      schema:
        type: string
    chunkHash:
      name: chunkHash
      description: 32 byte chunk blake3 hash, hex encoded
      in: path
      required: true
      schema:
        type: string
        minLength: 64
        maxLength: 64

    snapshotID:
      name: snapshotID
      description: ID of a snapshot
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 0

  responses:
    GlobalError:
      description: An error occured
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  # any object except Error starts with '__'
  # any other types start with '_' except the "main" ones
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required: [code, message]


    ### base models
    __UserID:
      type: object
      properties:
        userID:
          type: integer
          format: int64
      required: [userID]
    __UserName:
      type: object
      properties:
        userName:
          type: string
      required: [userName]

    __RoleID:
      type: object
      properties:
        roleID:
          type: integer
          format: int32
      required: [roleID]
    __RoleName:
      type: object
      properties:
        roleName:
          type: string
      required: [roleName]

    _Perm:
      type: integer
      format: int32
    __PermID:
      type: object
      properties:
        permID:
          $ref: "#/components/schemas/_Perm"
      required: [permID]
    __PermName:
      type: object
      properties:
        permName:
          type: string
      required: [permName]


    _Chunk:
      type: string
      format: binary

    ### User schemas
    UserNew:
      $ref: "#/components/schemas/__UserName"
    User:
      allOf:
        - $ref: "#/components/schemas/__UserID"
        - $ref: "#/components/schemas/__UserName"
        - $ref: "#/components/schemas/__RoleID"
    UserNewReturn:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            token:
              type: string
          required: [token]

    ### Role schemas
    RoleNew:
      $ref: "#/components/schemas/__RoleName"
    Role:
      allOf:
        - $ref: "#/components/schemas/__RoleID"
        - $ref: "#/components/schemas/__RoleName"

    ### Permission schemas
    PermWithName:
      allOf:
        - $ref: "#/components/schemas/__PermID"
        - $ref: "#/components/schemas/__PermName"
    PermNameArray:
      type: array
      items: 
        type: string
    PermDiff:
      type: object
      properties:
        add:
          $ref: "#/components/schemas/PermNameArray" 
        remove:
          $ref: "#/components/schemas/PermNameArray" 
      required: [add, remove]

    ### Repo schemas
    Repos:
      type: array
      items:
        type: string

    ### Branch schemas
    Branches:
      type: array
      items:
        type: string

    ### Snapshot Schemas
    __SnapshotIDObject: # ogen removes '_' which would make it conflict with _SnapshotID so added Object
      type: object
      properties:
        snapshotID:
          type: integer
          format: int64
      required: [snapshotID]
    __ParentSnapshotID:
      type: object
      properties:
        parentSnapshotID:
          type: integer
          format: int64
      required: [parentSnapshotID]


    __File:
      type: object
      properties:
        chunkHashes:
          type: array
          items: 
            type: string
        hash:
          type: string
        path:
          type: string
      required: [chunkHashes, hash, path]
    Files:
      type: object
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/__File"
      required: ["files"]

    SnapshotNew:
      $ref: "#/components/schemas/Files"
    SnapshotFiles:
      allOf:
        - $ref: "#/components/schemas/Files"
        - $ref: "#/components/schemas/__ParentSnapshotID"

security:
  - bearerAuth: []

paths:
  /health:
    get:
      summary: Get health of server
      operationId: get-health
      tags:
        - System
      security: []
      responses:
        "200": {}
        default:
          $ref: "#/components/responses/GlobalError"


  /users:
    get:
      summary: Get all users
      operationId: get-users
      tags:
        - Users
      responses:
        "200":
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        default:
          $ref: "#/components/responses/GlobalError"
    post:
      summary: Create new user
      operationId: post-users
      tags:
        - Users
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserNew"
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNewReturn"
        default:
          $ref: "#/components/responses/GlobalError"
  /users/me:
    get:
      summary: Get id of the token bearer
      operationId: get-me
      tags:
        - Users
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          $ref: "#/components/responses/GlobalError"

  /users/{userID}:
    parameters:
      - $ref: "#/components/parameters/userID"
    get:
      summary: Get info about user
      operationId: get-user
      tags:
        - Users
      responses:
        "200":
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          $ref: "#/components/responses/GlobalError"
  /users/{userID}/name:
    parameters:
      - $ref: "#/components/parameters/userID"
    put:
      summary: Change username of user
      operationId: put-user-name
      tags:
        - Users
      responses:
        "200": {}
        default:
          $ref: "#/components/responses/GlobalError"
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/__UserName"
  /users/{userID}/repos:
    parameters:
      - $ref: "#/components/parameters/userID"
    get:
      summary: Get all repos owned by userID
      operationId: get-user-repos
      tags:
        - Users
      responses:
        "200":
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Repos"
        default:
          $ref: "#/components/responses/GlobalError"

  /users/{userID}/repos/{repoName}:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/repoName"
    put:
      summary: Create new repo and a default branch "main"
      operationId: put-user-repo
      tags:
        - Users
      responses:
        "201": {}
        default:
          $ref: "#/components/responses/GlobalError"

  /users/{userID}/repos/{repoName}/branches:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/repoName"
    get:
      summary: Get all branches in repo
      operationId: get-user-repo-branches
      tags:
        - Users
      responses:
        "200": 
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Branches"
        default:
          $ref: "#/components/responses/GlobalError"
  /users/{userID}/repos/{repoName}/branches/{branchName}:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/repoName"
      - $ref: "#/components/parameters/branchName"
    put:
      summary: Create new branch in repo
      operationId: put-user-repo-branch
      tags:
        - Users
      responses:
        "201": {}
        default:
          $ref: "#/components/responses/GlobalError"

  /users/{userID}/repos/{repoName}/branches/{branchName}/current:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/repoName"
      - $ref: "#/components/parameters/branchName"
    get:
      summary: Get current snapshot the branch points to
      operationId: get-branch-head
      tags:
        - Users
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/__SnapshotIDObject"
        "404":
          description: The branch does not have a head
        default:
          $ref: "#/components/responses/GlobalError"

  /users/{userID}/repos/{repoName}/branches/{branchName}/snapshots:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/repoName"
      - $ref: "#/components/parameters/branchName"
    post:
      summary: Create new snapshot
      operationId: post-user-repo-branch-snapshot
      tags:
        - Users
      responses:
        "201": {}
        "424": 
          description: Some of the provided chunks are missing which are returned
          content: 
            application/json:
              schema:
                type: object
                properties:
                  chunkHashes:
                    type: array
                    items: 
                      type: string
        default:
          $ref: "#/components/responses/GlobalError"
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/SnapshotNew"

  /users/{userID}/repos/{repoName}/branches/{branchName}/snapshots/{snapshotID}:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/repoName"
      - $ref: "#/components/parameters/branchName"
      - $ref: "#/components/parameters/snapshotID"
    get:
      summary: Get all files and chunks for snapshot
      operationId: get-snapshot
      tags:
        - Users
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SnapshotFiles"
        default:
          $ref: "#/components/responses/GlobalError"






  /roles:
    get:
      summary: Get all roles
      operationId: get-roles
      tags:
        - Roles
      responses:
        "200": 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"
        default:
          $ref: "#/components/responses/GlobalError"
    post:
      summary: Create new role
      operationId: post-roles
      tags:
        - Roles
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
        default:
          $ref: "#/components/responses/GlobalError"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleNew"


  /roles/{roleID}/name:
    parameters:
      - $ref: "#/components/parameters/roleID"
    put:
      summary: Update role name
      operationId: put-role-name
      tags:
        - Roles
      responses:
        "200": {}
        default:
          $ref: "#/components/responses/GlobalError"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/__RoleName"


  /roles/{roleID}/perms:
    parameters:
      - $ref: "#/components/parameters/roleID"
    get:
      summary: Get all permissions the role has
      operationId: get-role-perms
      tags:
        - Permissions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermNameArray"
        default:
          $ref: "#/components/responses/GlobalError"
    patch:
      summary: Patch perms for role
      operationId: patch-role-perms
      tags:
        - Permissions
      responses:
        "200": {}
        "422":
          description: There are invalid perm names in 'add' or 'delete'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          $ref: "#/components/responses/GlobalError"
        default:
          $ref: "#/components/responses/GlobalError"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PermDiff"
    put:
      summary: Set perms for role
      operationId: put-role-perms
      tags:
        - Permissions
      responses:
        "200": {}
        "422":
          description: There are invalid perm names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          $ref: "#/components/responses/GlobalError"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PermNameArray"
  /perms:
    get:
      summary: Get all available permissions
      operationId: get-perms
      tags:
        - Permissions
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PermWithName"
        default:
          $ref: "#/components/responses/GlobalError"

  /chunks/{chunkHash}:
    parameters:
      - $ref: "#/components/parameters/chunkHash"
    put:
      summary: Upload chunk
      operationId: put-chunk
      tags:
        - Chunk
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: "#/components/schemas/_Chunk"
      responses:
        "200":
          description: Chunk already exists
        "201": {}
        default:
          $ref: "#/components/responses/GlobalError"

